name: Node.js Job

on:
  schedule:
    - cron: '*/14 * * * *'

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run the script
        run: node index.js
